name: Deploy to Vercel

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Change to backend directory
        run: cd backend

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Set Django environment variables
        run: |
          echo "DJANGO_ENV=production" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Apply migrations
        run: |
          cd backend
          . venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      - name: Inyectar datos ficticios para pruebas
        run: |
          cd backend
          . venv/bin/activate
          psql "${{ secrets.DATABASE_URL }}" -f fictionalData.sql

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd backend
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --yes
