name: Deploy API with ngrok

on:
  push:
    branches:
      - backend
  pull_request:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: |
          cd backend
          source venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      - name: Load test data
        run: |
          cd backend
          source venv/bin/activate
          sqlite3 db.sqlite3 ".read fictionalData.sql"

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok  # Asegúrate de que ngrok sea ejecutable
          
      - name: Authenticate ngrok
        run: |
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}  # Ejecuta ngrok desde el mismo directorio

      - name: Expose API with ngrok
        run: |
          cd backend
          source venv/bin/activate
          nohup python manage.py runserver 0.0.0.0:8000 & 
          sleep 10  # Esperar que el servidor inicie
          ./ngrok http 8000 --log=stdout > ngrok.log &  # Ejecutar ngrok desde el mismo directorio
          sleep 10  # Esperar para que ngrok establezca la conexión
          URL=$(tail -n 10 ngrok.log | grep -o 'https://[a-z0-9]*\.ngrok.io')  # Obtener la URL
          echo "API URL: $URL"
