name: Deploy to Vercel

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Change to backend directory
        run: cd backend

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          . venv/bin/activate  # En Windows: .\venv\Scripts\activate
          pip install -r requirements.txt

      - name: Set Django environment to test
        run: echo "DJANGO_ENV=test" >> $GITHUB_ENV  # Establece la variable de entorno para el entorno de pruebas

      - name: Apply migrations
        run: |
          cd backend
          . venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      - name: Inyectar datos ficticios para pruebas
        run: |
          cd backend
          . venv/bin/activate
          sqlite3 db.sqlite3 ".read fictionalData.sql"  # Ejecutar el script SQL para insertar datos ficticios

      - name: Ejecutar el servidor Django (opcional, solo para verificar que está funcionando)
        run: |
          cd backend
          . venv/bin/activate
          python manage.py runserver &  # Ejecutar el servidor en segundo plano (aunque no es necesario para Vercel)

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd backend
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --yes
